&emsp;&emsp;大家一定还记得上一章中，我们详解介绍了一些幽灵般的错误。我想，码农的痛苦也莫过于此了。多线程本身就是非常容易引起这类错误的。如果你使用了线程池，那么**这种幽灵错误可能会变得更加常见**。

&emsp;&emsp;下面来看一个简单的案例，首先，我们有一个Runnable接口，它用来计算两个数的商：
```
public class DivTask implements Runnable {
    int a,b;

    public DivTask(int a, int b) {
        this.a = a;
        this.b = b;
    }

    public void run() {
        double re=a/b;
        System.out.println(re);
    }
}

```

&emsp;&emsp;如果程序运行了这个任务，那么我们期望它可以打印出给定两个数的商。现在我们的构造几个这样的任务，希望程序可以为我们计算一组给定数组的商：
```
public static void main(String[] args) {
    ThreadPoolExecutor pools = new ThreadPoolExecutor(0, Integer.MAX_VALUE,0L, TimeUnit.SECONDS,new SynchronousQueue<Runnable>());

    for (int i=0;i<5;i++) {
        pools.submit(new DivTask(100, i));
    }
}
```

&emsp;&emsp;上述代码将DivTask提交到线程池，从这个for循环来看，我们应该会得到5个结果，分别是100除以给定的i后的商。但是如果你真的运行程序，你得到的全部结果是：
```
100.0
33.0
25.0
50.0
```

&emsp;&emsp;你没看错！只有4个输出。也就说是程序漏算了一组数据！但更不幸的是，程序没有任何日志，没有任何错误提示，就好像一切都正常一样。在这个简单的案例中，只要不稍有经验，你就能发现，作为除数的i取到了0，这个缺失的值很可能是由于除以0导致的。但在稍复杂的业务场景中这种错误足可以让你几天萎靡不振。

&emsp;&emsp;因此，使用线程池虽然是件好事，但是还是得处处留意这些“坑”。线程池很有可能会“吃”掉程序抛出的异常，导致我们队程序的错误一无所知。

&emsp;&emsp;异常堆栈对于程序员的重要性就好像指南针对于茫茫大海上的船只。没有指南针，船只只能更艰难的寻找方向，没有异常堆栈，排查问题时，也只能像大海捞针那样，慢慢琢磨了。我的一个领导曾经说过：最鄙视那些出错不打印异常堆栈的行为！我相信，任何一个得益于异常堆栈而快速定位问题的程序员来说，一定对这句话深有体会。所以，**这里我们将和大家讨论向线程池讨回异常堆栈的方法**。

&emsp;&emsp;一种最简单的方法，就是放弃submit()，改用execute()。将上述的任务提交代码改成：
```
pools.execute(new DivTask(100, i));
```

&emsp;&emsp;或者你使用下面的方法改造你的submit():
```
Future re = pools.submit(new DivTask(100, i));
re.get();
```

&emsp;&emsp;上面两种方法都可以得到部分堆栈信息，如下所示：
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at DivTask.main(DivTask.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArithmeticException: / by zero
	at DivTask.run(DivTask.java:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

&emsp;&emsp;注意了，我这里说的是部分。这是因为从这两个异常堆栈中我们只能知道异常是在哪里抛出的。但是我们还希望得到另外一个重要的信息，那就是这个任务到底是在哪里提交的？而任务的具体提交位置已经被线程池完全淹没了。顺着堆栈，我们最多只能找到线程池中的调度流程，而这对于我们几乎是没有价值的。

&emsp;&emsp;既然这样，我们只能自己动手，丰衣足食了！为了今后少加几天班，我们还是非常有必要将堆栈的信息彻底挖出来！扩展我们的ThreadPoolExecutor线程池，让它在调度任务之前，先保存一下提交任务线程的堆栈信息。如下所示：
```
public class TraceThreadPoolExecutor extends ThreadPoolExecutor {
    public TraceThreadPoolExecutor(int corePoolSize, int maximumPoolSize, long keepAliveTime, TimeUnit unit, BlockingQueue<Runnable> workQueue) {
        super(corePoolSize, maximumPoolSize, keepAliveTime, unit, workQueue);
    }

    @Override
    public Future<?> submit(Runnable task) {
        return super.submit(wrap(task, clientTrace(), Thread.currentThread().getName()));
    }

    @Override
    public void execute(Runnable command) {
        super.execute(wrap(command, clientTrace(), Thread.currentThread().getName()));
    }
    
    private Exception clientTrace() {
        return new Exception("Client stack trace");
    }
    
    private Runnable wrap(final Runnable task, final Exception clientStack, String ClinetThreadName) {
        return new Runnable() {
            public void run() {
                try {
                    task.run();
                } catch (Exception e) {
                    clientStack.printStackTrace();
                    try {
                        throw e;
                    } catch (Exception e1) {
                        e1.printStackTrace();
                    }
                }
            }
        };
    }
}
```

&emsp;&emsp;在第23行代码中，wrap()方法的第2个参数为一个异常，里面保存着提交任务的线程的堆栈信息。该方法将我们传入的Runnable任务进行一层包装，使之能处理异常信息。当任务发生异常时，这个异常会被打印。

&emsp;&emsp;好了，现在我们使用我们的新成员（TraceThreadPoolExecutor）来尝试执行转代码了：
```
public static void main(String[] args) throws ExecutionException, InterruptedException {
        ThreadPoolExecutor pools = new TraceThreadPoolExecutor(0, Integer.MAX_VALUE,0L, TimeUnit.SECONDS,new SynchronousQueue<Runnable>());

        for (int i=0;i<5;i++) {
            pools.execute(new DivTask(100, i));
        }
    }
```

&emsp;&emsp;执行上述代码，就可以得到以下信息：
```
50.0
33.0
25.0
100.0
java.lang.Exception: Client stack trace
	at cyclicbarrier.TraceThreadPoolExecutor.clientTrace(TraceThreadPoolExecutor.java:27)
	at cyclicbarrier.TraceThreadPoolExecutor.execute(TraceThreadPoolExecutor.java:23)
	at DivTask.main(DivTask.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
java.lang.ArithmeticException: / by zero
	at DivTask.run(DivTask.java:14)
	at cyclicbarrier.TraceThreadPoolExecutor$1.run(TraceThreadPoolExecutor.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

&emsp;&emsp;熟悉的异常又回来了！现在，我们不仅可以得到异常发生的Runnable时实现内的信息，我们也知道了这个任务是在哪里提交的（提示在第几行代码处）。如此丰富的信息，我相信可以帮助我们瞬间定位问题！